import { FadeIn } from "@/components/ui/motion";
import { GlassCard } from "@/components/ui/glass-card";
import { MetricList, MiniMetric, SectionHeading } from "@/components/ui/kpi-widgets";

type ChannelRow = {
  name: string;
  share: string;
};

type RecoveryRow = {
  name: string;
  value: string;
  tone?: "default" | "amber";
};

const channelRows: ChannelRow[] = [
  { name: "Google Search", share: "38%" },
  { name: "Website Chat", share: "24%" },
  { name: "Inbound Calls", share: "22%" },
  { name: "Email Follow-Up", share: "16%" },
];

const recoveryRows: RecoveryRow[] = [
  { name: "Missed calls", value: "6 pending", tone: "amber" },
  { name: "Incomplete payments", value: "3 pending" },
  { name: "Cold leads to re-engage", value: "9 queued" },
];

export function DashboardPreviewSection() {
  return (
    <section id="dashboard" className="section-y">
      <div className="container-brand">
        <div className="grid items-start gap-10 lg:grid-cols-[0.9fr_1.1fr]">
          <FadeIn>
            <div>
              <SectionHeading
                align="left"
                eyebrow="Revenue Visibility Built In"
                title="See what BookedAI.au actually generates."
                body="BookedAI.au does not stop at handling enquiries. It helps you measure bookings won, revenue created, opportunities missed, and the channels driving the best performance."
              />

              <div className="mt-8 space-y-3 text-sm text-brand-muted">
                <div>• Revenue generated by source</div>
                <div>• Search to booking conversion %</div>
                <div>• Call to booking conversion %</div>
                <div>• Email follow-up recovery %</div>
                <div>• Missed revenue and recovered opportunities</div>
                <div>• Payment completion and commission summary</div>
              </div>
            </div>
          </FadeIn>

          <FadeIn delay={0.08}>
            <GlassCard className="p-6">
              <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
                <MiniMetric label="Revenue Generated" value="$18,420" tone="green" />
                <MiniMetric label="Total Bookings" value="86" />
                <MiniMetric label="Avg Booking Value" value="$214" tone="blue" />
                <MiniMetric label="Search → Booking" value="11.4%" tone="green" />
                <MiniMetric label="Call → Booking" value="24.1%" tone="green" />
                <MiniMetric label="Email → Booking" value="8.9%" />
                <MiniMetric label="Missed Revenue" value="$2,160" tone="amber" />
                <MiniMetric label="Recovered Value" value="$780" tone="green" />
                <MiniMetric label="Commission Due" value="$1,842" />
              </div>

              <div className="mt-6 grid gap-4 lg:grid-cols-2">
                <MetricList title="Top-performing channels">
                  {channelRows.map((row) => (
                    <div key={row.name} className="flex justify-between">
                      <span className="text-brand-muted">{row.name}</span>
                      <span className="text-brand-text">{row.share}</span>
                    </div>
                  ))}
                </MetricList>

                <MetricList title="Revenue opportunities to recover">
                  {recoveryRows.map((row) => (
                    <div key={row.name} className="flex justify-between">
                      <span className="text-brand-muted">{row.name}</span>
                      <span className={row.tone === "amber" ? "text-brand-amber" : "text-brand-text"}>
                        {row.value}
                      </span>
                    </div>
                  ))}
                </MetricList>
              </div>
            </GlassCard>
          </FadeIn>
        </div>
      </div>
    </section>
  );
}
